# Generated by Django 4.0.4 on 2022-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_image_gallery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='categories',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('posted',)},
        ),
    ]
